### ISSUE TITLE
PLINK-635: freezone not supported; bug in SPFormAuthenticationMechanism?

### ISSUE THREAD

**Issue by The-Alchemist** [picketlink/picketlink-bindings#112]
The corresponding issue for PicketLink is [https://issues.jboss.org/browse/PLINK-635](PLINK-635).

Basically, ```org.picketlink.identity.federation.bindings.wildfly.sp.SPServletExtension``` doesn't seem to support "freezones".  There's not much code in the SPServletExtension, so I'm guessing the bug is in SPFormAuthenticationMechanism.

SP resources without auth-constraints are not respected as such, and still redirect.

Anyone have any workarounds?

P.S. Forum discussion at https://developer.jboss.org/thread/251829?start=0&tstart=0.

**Comment by pedroigor** [comment]
References https://issues.jboss.org/browse/PLINK-635
