### ISSUE TITLE
GenericPrincipal(ctx.getRealm(), username, null, roles) is not working for Tomcat7 ?

### ISSUE THREAD

**Issue by aungthawaye** [picketlink/picketlink-bindings#126]
Hi,

I setup IDP and SP inside my Tomcat 7 (locahost). Then I login IDP and tested http://localhost:8080/sales-saml11/ I got this error:

java.lang.NoSuchMethodError: org.apache.catalina.realm.GenericPrincipal.<init>(Lorg/apache/catalina/Realm;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)V
    org.picketlink.identity.federation.bindings.tomcat.sp.SPUtil.createGenericPrincipal(SPUtil.java:81)

So when I checked SPUtil is using Tomcat 6's GenericPrincipal class ? Because of that, it is not working in Tomcat 7 ?

Thanks,
Aung

**Comment by FibreFoX** [comment]
http://stackoverflow.com/questions/9826706/tomcat-migration-authentication-issue

shameless quote ;)

> 
> I don't see that AuthRealm class in the Tomcat docs. I guess it's a custom Realm which was programmed against Tomcat 6 and now the API has changed.
> 
> The object org.apache.catalina.realm.GenericPrincipal changed from version 6 to version 7 and now it doesn't have the getRealm() method.

**Comment by pedroigor** [comment]
This repository is no longer maintained and is archived. For more details, please take a look at http://picketlink.org/keycloak-merge-faq.
