### ISSUE TITLE
picketlink-bindings  don't include the license file

### ISSUE THREAD

**Issue by puntogil** [picketlink/picketlink-bindings#132]
Hi
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
Thanks in advance
Regards

**Comment by pedroigor** [comment]
This repository is no longer maintained and is archived. For more details, please take a look at http://picketlink.org/keycloak-merge-faq
